export const GRIDCONFIG = {
  lineWidth: 2,
  strokeStyle: "#C4C7C5",
  cellHeight: 25,
  cellWidth: 100,
  colWidth: 46,
  rowHeight: 25,
} as const;

export const CUSTOM_FONTS: string[] = [
  "open-sans",
  "barlow-condensed",
  "caveat",
  "crimson-text",
  "dancing-script",
  "inter",
  "lato",
  "lobster",
  "montserrat",
  "nunito-sans",
  "oswald",
  "pacifico",
  "poppins",
  "quicksand",
  "roboto",
  "roboto-mono",
  "rubik",
  "ubuntu",
];

export const FONTS: Record<string, string> = {
  "open-sans": "Open Sans",
  "barlow-condensed": "Barlow Condensed",
  caveat: "Caveat",
  "crimson-text": "Crimson Text",
  "dancing-script": "Dancing Script",
  inter: "Inter",
  lato: "Lato",
  lobster: "Lobster",
  montserrat: "Montserrat",
  "nunito-sans": "Nunito Sans",
  oswald: "Oswald",
  pacifico: "Pacifico",
  poppins: "Poppins",
  quicksand: "Quicksand",
  roboto: "Roboto",
  "roboto-mono": "Roboto Mono",
  rubik: "Rubik",
  ubuntu: "Ubuntu",
};
